### ISSUE TITLE
Allow only one instance to run at the same time

### ISSUE THREAD

**Issue by probonopd** [mrclksr/DSBExec#3]
I have set up the system to show DSBExec when Alt-F2 is pressed.
It would be good to allow only one instance to run at the same time so that when one presses Alt-F2 multiple times, only one window is shown.

E.g., using
* https://stackoverflow.com/a/28172162 or
* https://github.com/itay-grudev/SingleApplication

**Comment by probonopd** [comment]
That was quick, thank you very much. :+1: 

Should appear in https://github.com/helloSystem/ISO/releases/tag/continuous-hello in one of the next builds.

**Comment by mrclksr** [comment]
> That was quick, thank you very much.

No problem :)

> Should appear in https://github.com/helloSystem/ISO/releases/tag/continuous-hello in one of the next builds.

Nice :)
